server:
  port: 56085
  servlet:
    context-path: /sj-sms

spring:
  application:
    name: sj-sms

  main:
    allow-bean-definition-overriding: true



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
#    host: 192.168.203.128
#    host: 172.16.1.241
    cluster:
      nodes: 172.16.1.241:6379,172.16.1.242:6379
      max-redirects: 2
    #    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 10000
      shutdown-timeout: 100
    timeout: 10000

sms:
  qcloud:
    appId: 0
    appKey: appKey
    templateId: 0
    sign: 签名

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml
  level:
    com.djh.shanjupay.sms: debug

