server:
  port: 56040
  servlet:
    context-path: /merchant

spring:
  application:
    name: sj-merchant
  # 启用bean覆盖 spring boot2.1以上版本需指定
  main:
    allow-bean-definition-overriding: true
  # nacos 配置
  cloud:
    nacos:
      discovery:
        # nacos 地址
        server-addr: 127.0.0.1:8848
#        server-addr: 192.168.203.128:8848
        # 公司nacos开发环境namespace
        namespace: 65a3eb11-8431-4479-a13a-87c938ef97ee
        # 本机nacos开发环境
#        namespace: 67402c73-2d27-4a13-84b8-8ad1d94836b1
        cluster-name: DEFAULT
  # springMVC文件上传配置
  servlet:
    multipart:
      # 默认支持文件上传
      enabled: true
      # 临时文件存放目录
      location:
      # 是否支持写入磁盘
      file-size-threshold: 0
      # 最大支持上传文件大小
      max-file-size: 1GB
      # 最大支持请求大小
      max-request-size: 30MB


logging:
  config: classpath:log4j2.xml
  level:
    com.djh.shanjupay.merchant: debug

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  maxAutoRetries: 0